---
- name: Create a Tenant in MSO
  hosts: nd
  connection: local
  gather_facts: no

  tasks:
  - name: Add a new tenant
    cisco.mso.mso_tenant:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      tenant: Tesla
      display_name: Tesla
      description: This creates a Tenant Tesla
      sites:
      - San Francisco
      - New York
      validate_certs: no
      state: present

