---
# Example Playbook using aci_rest module
- name: Configuration using ACI REST
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:
  - name: Enabling Endpoint loop prevention
    cisco.aci.aci_rest:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      private_key: "{{ key }}"
      path: /api/node/mo/uni/infra/epLoopProtectP-default.json
      method: post
      content: |
        {
          "epLoopProtectP": {
            "attributes": {
              "action": "",
              "adminSt": "enabled",
              "loopDetectIntvl": "60",
              "loopDetectMult": "4",
              "dn":"uni/infra/epLoopProtectP-default"
            }
          }
        }
      validate_certs: no

  - name: Setting COOP policy to Strict
    cisco.aci.aci_rest:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      private_key: "{{ key }}"
      path: /api/node/mo/uni/fabric/pol-default.json
      method: post
      content: |
        {
          "coopPol": {
            "attributes":{
              "type":"strict",
              "dn":"uni/fabric/pol-default"
            }
          }
        }
      validate_certs: no

  - name: Set Enforce Subnet check to true
    cisco.aci.aci_rest:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      private_key: "{{ key }}"
      path: /api/node/mo/uni/infra/settings.json
      method: post
      content: |
        {
          "infraSetPol": {
            "attributes": {
              "enforceSubnetCheck":"true",
              "dn":"uni/infra/settings"
            }
          }
        }
      validate_certs: no

