# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:
  - name: Create Tenant
    cisco.aci.aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      private_key: "{{ key }}"
      tenant: "CiscoLive"
      description: "Tenant configured by Ansible"
      validate_certs: no
      state: present

  - name: Create VRF
    cisco.aci.aci_vrf:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      private_key: "{{ key }}"
      tenant: "CiscoLive"
      vrf: "VRF1"
      description: "VRF configured by Ansible"
      validate_certs: no
      state: present

