---
# ACI Query Playbook
- name: Fabric Information
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:
  - name: Query all tenants
    cisco.aci.aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      private_key: "{{ key }}"
      validate_certs: no
      state: query
    register: all_tenants
  
  # Print out all Tenants
  - name: Print out tenants
    debug:
      msg:
      - "------- Tenant list from APIC -------"
      - "{{ all_tenants | json_query('current[].fvTenant.attributes.name') }}"
